news/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.index, name = 'index'),
    path('about', views.about, name = 'about'),
    path('contact', views.contact, name = 'contact'),
    path('news-details/<slug>',views.news_details,name= 'news-details'),
    path('slider-details/<slug>',views.slider_details,name= 'slider-details' ),
    path('latestnews-details/<slug>',views.latestnews_details,name= 'latestnews-details' ),
    path('login',views.user_login,name='login'),
    path('register',views.register,name='register'),
    path('users',views.users,name='users'),
    path('logout',views.user_logout,name='logout'),
    path('password-reset',auth_views.PasswordResetView.as_view(template_name = 'pages/accounts/password-reset.html'),name ='password-reset'),
    path('password-reset-confirm/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name = 'pages/accounts/password-reset-confirm.html'),name ='password-reset-confirm'),
    path('password_reset_done',auth_views.PasswordChangeDoneView.as_view(template_name = 'pages/accounts/password_reset_done.html'),name ='password_reset_done'),
    path('password_reset_complete',auth_views.PasswordResetCompleteView.as_view(template_name = 'pages/accounts/password_reset_complete.html'),name ='password_reset_complete')
    
]

newsapi/urls.py
from django.urls import path,include
from rest_framework import routers
from .views import *

app_name = 'newsapi'

router = routers.DefaultRouter()
router.register('',NewsApiDetails)
urlpatterns = [
    path('',include(router.urls))
]

newsfeed/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from  django.conf.urls.static import static

urlpatterns = [
    path('',include('news.urls')),
    path('newsapi',include('newsapi.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.admin import User
from ckeditor.fields import RichTextField


class Category(models.Model):
    cat_name = models.CharField(max_length= 100, unique=True)
    status = models.BooleanField(default=0)


    def __str__(self):
        return self.cat_name

    class Meta:
         verbose_name_plural = 'Category'



class News(models.Model):
    posted_date = models.DateTimeField(default=timezone.now)
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    posted_by = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, upload_to='news')
    description = RichTextField()
    status = models.BooleanField(default=0)


    class Meta:
         verbose_name_plural = 'News'


class Slider(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(blank=True, upload_to='news')
    description = RichTextField()
    status = models.BooleanField(default=0)

    def __str__(self):
        return self.title


    class Meta:
         verbose_name_plural = 'Slider'

class LNews(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(blank=True, upload_to='news')
    description = RichTextField()
    status = models.BooleanField(default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Latest News'



class Contact(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.EmailField()
    message = RichTextField()

    def __str__(self):
        return f'{self.first_name}{self.last_name}'

newsapi/models.py
from django.db import models

# Create your models here.

news/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('first_name','last_name','email','message')

news/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import ContactForm


def index(request):
    content = {
        'title': 'home',
        'sliderData': Slider.objects.all(),
        'newsDetailsData': News.objects.all(),

    }
    return render(request, 'pages/index.html', content)


def about(request):
    content = {
        'title': 'about'
    }
    return render(request, 'pages/about.html', content)


def contact(request):
    content = {
        'title': 'contact'
    }
    return render(request, 'pages/contact.html', content)


def news_details(request, slug):
    content = {
        'newsDetailsData': News.objects.filter(slug=slug)
    }
    return render(request, 'pages/news-details.html', content)


def slider_details(request, slug):
    content = {
        'sliderData': Slider.objects.filter(slug=slug)
    }

    return render(request, 'pages/slider-details.html', content)

def latestnews_details(request, slug):
    content = {
        'latestnewsData': LNews.objects.filter(slug=slug)
    }

    return render(request, 'pages/latestnews-details.html', content)



def user_login(request):
    if request.method == 'POST':
        data = AuthenticationForm(data=request.POST)
        if data.is_valid():
            user = data.get_user()
            login(request, user)
            return redirect('users')
        else:
            return redirect('login')
    else:
        content = {
            'loginForm': AuthenticationForm
        }
    return render(request, 'pages/accounts/login.html', content)


def register(request):
    if request.method == 'POST':
        data = UserCreationForm(request.POST)
        if data.is_valid():
            data.save()
            messages.success(request, 'User was successfully register')
            return redirect('register')
        else:
            return redirect('register')
    else:
        content = {
            'userRegister': UserCreationForm
        }
        return render(request, 'pages/accounts/register.html', content)

def contact (request):
    if request.method == 'POST':
       form = ContactForm(request.POST)
       if form.is_valid():
           form.save()
           messages.success(request,'you have sucessfully contacted')
           return redirect('contact')
       else:
           return redirect('contact')
    else:
        form = ContactForm()
    content = {
         'form': form
    }
    return render(request,'pages/contact.html',content)




@login_required(login_url='login')
def users(request):
    content = {
        'title': 'User'
    }
    return render(request, 'pages/user.html', content)


def user_logout(request):
    if request.method == 'POST':
        logout(request)
        return redirect('login')
    else:
        return HttpResponse('Invalid Access')

newsapi/views.py
from django.shortcuts import render

from .serializers import NewsSerializer

from news.models import News
from rest_framework import viewsets


class NewsApiDetails(viewsets.ModelViewSet) :
    queryset = News.objects.all()
    serializer_class = NewsSerializer

news/templates/layouts/footer.html
{% load static %}
<footer id="footer">
    <div class="footer_top">
      <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4">
          <div class="footer_widget wow fadeInDown">
            <h2>Pages</h2>
            <ul class="tag_nav">
              <li><a href="{% url 'about' %}">About Us</a></li>
              <li><a href="{% url 'contact' %}">Contact Us</a></li>
            </ul>
          </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4">
          <div class="footer_widget wow fadeInRightBig">
            <h2>Contact</h2>
            <p>This is official news site, 9808270974.</p>
            <address>
            Putalisadak,Kathmandu,Bagmati,Nepal
            </address>
          </div>
        </div>
      </div>
    </div>
  </footer>
</div>
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/wow.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/slick.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.li-scroller.1.0.js' %}"></script>
<script src="{% static 'assets/js/jquery.newsTicker.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.fancybox.pack.js' %}"></script>
<script src="{% static 'assets/js/custom.js' %}"></script>
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v5.0"></script>
</body>
</html>

news/templates/layouts/header.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<title>NewsFeed</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/animate.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/font.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/li-scroller.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/slick.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/jquery.fancybox.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/theme.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
<script src="{% static 'assets/js/html5shiv.min.js' %}"></script>
<script src="{% static 'assets/js/respond.min.js' %}"></script>
</head>
<body>
<a class="scrollToTop" href="#"><i class="fa fa-angle-up"></i></a>
<div class="container">

news/templates/layouts/nav-bar.html
<section id="navArea">
    <nav class="navbar navbar-inverse" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav main_nav">
          <li class="active"><a href="{% url 'index' %}"><span class="fa fa-home desktop-home"></span><span class="mobile-show">Home</span></a></li>
          {% for category in categoryData %}
          {% if category.news_set.all %}
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              {{category.cat_name}}</a>
            <ul class="dropdown-menu" role="menu">
              {% for news in category.news_set.all %}
              <li><a href="{% url 'news-details' news.slug %}">{{ news.name }}</a></li>
              {% endfor %}
            </ul>
          </li>
          {% else %}
          <li><a href="">{{category.cat_name}}</a></li>
          {% endif %}
          {% endfor %}

        </ul>
      </div>
    </nav>
  </section>

news/templates/layouts/top-header.html
{% load static %}
<header id="header">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="header_top">
          <div class="header_top_left">
            <ul class="top_nav">
              <li><a href="{% url 'index' %}">Home</a></li>
              <li><a href="{% url 'about' %}">About</a></li>
              <li><a href="{% url 'contact' %}">Contact</a></li>
              <li><a href="{% url 'login' %}">Login</a></li>
              <li><a href="{% url 'register' %}">Register</a></li>
              <li>
                  {% if user.is_authenticated %}
                  <form action="{% url 'logout' %}" method="post">
                      {% csrf_token %}
                      <button class="btn btn-success">Logout</button>
                  </form>
                  {% endif %}
              </li>
            </ul>
          </div>
          <div class="header_top_right">
            <p>{% now 'Y_Md_D' %}
</p>
          </div>
        </div>
      </div>
      <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="header_bottom">
          <div class="logo_area"><a href="{% url 'index' %}" class="logo"><img src="{% static 'assets/icons/logo.png' %}" alt=""></a></div>
          <div class="add_banner"><a href="{% url 'index' %}"><img src="{% static 'assets/icons/banner.gif' %}" alt=""></a></div>
        </div>
      </div>

    </div>
  </header>

news/templates/master/master.html
{% include 'layouts/header.html' %}
{% include 'layouts/top-header.html' %}
{% include 'layouts/nav-bar.html' %}
{% block content %}
{% endblock %}
{% include 'layouts/footer.html' %}

news/templates/pages/about.html
{% extends 'master/master.html'%}
{% block content %}
<section id="contentSection">
    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-8">
        <div class="left_content">
          <div class="contact_area">
            <h2>About Us</h2>
                  <img src="/media/news/about-us-banner-new.jpg" class="img-responsive" alt="">
                  <p>
                    it is likely to reach to unsupported or o <strong>Since it is a news service</strong> it has different updated internal and external links to facts represented as news with comments and opinions given by others on that topic,enabling<br> viewers to share their…show more content… n this way readers are aware of the latest news. The site is well designed and free, which make it one of the first choices for reading the news. But the coverage of technological significance is sparse unlike other sites which have expanded topics, with articles going into a little more in-depth; without becoming excessively technical... Antitrust coverage from Capitalism Magazine It's an online publication supporting capitalism that provides the public withimportant, efficient news, information and articles but not all at once.<br><br> Opinions and thoughts are freely written in this site with evidences and arguments supporting each thought .
                    Although links are accurately attached to their addresses but sometimesld information which may be lost in the archive. Accordingly each article has it own date kept in the article itself benefiting the reader. A navigator bar is providing on the right to choose your choice .It contain advertisements about capitalism books and other technological ads.It covered alot of advertisement for all ads associated to the computer and other production technology advertising for hardware with a lot of anew production showing products at their bet proices with a summary about each poroduct.
                  </p>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-4">
        <div class="latest_post">
          <h2><span>Latest News</span></h2>
          <div class="latest_post_container">
            <div id="prev-button"><i class="fa fa-chevron-up"></i></div>
            <ul class="latest_postnav">
              {% for lnews in latestnewsData %}
                  <li>
                    <div class="media"> <a href="{% url 'latestnews-details' lnews.slug %}" class="featured_img"> <img alt="" src="{{ lnews.image.url }}"></a>
                       <h2><span><a href="{% url 'latestnews-details' lnews.slug %}" class="catg_title">{{ lnews.title }}</a></span></h2>
                      <div class="media-body">  {{ lnews.description|slice:"255"|safe }} </div>
                    </div>
                  </li>
              {% endfor %}
            </ul>
            <div id="next-button"><i class="fa  fa-chevron-down"></i></div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

news/templates/pages/accounts/login.html
{% extends 'master/master.html'%}
{% block content %}
{% load crispy_forms_tags %}
<section id="contentSection">
    <h1>Login</h1>
    <hr>
    <form action="{% url 'login' %}"  method="post">
         {% csrf_token %}
         {{loginForm|crispy}}
         <button class="btn btn-success">Login</button>
    </form>
    <a href="{% url 'password-reset' %} " class="btn btn-danger btn-sm">Password Reset</a>
</section>
{% endblock %}

news/templates/pages/accounts/password-reset-confirm.html
{% extends 'master/master.html'%}
{% block content %}
{% load crispy_forms_tags %}
<section id="contentSection">
    <h1>Password Reset</h1>
    <hr>
    <form action=""  method="post">
         {% csrf_token %}
         {{form|crispy}}
         <button class="btn btn-success">send</button>
    </form>
</section>
{% endblock %}

news/templates/pages/accounts/password-reset.html
{% extends 'master/master.html'%}
{% block content %}
{% load crispy_forms_tags %}
<section id="contentSection">
    <h1>Password Reset</h1>
    <hr>
    <form action=""  method="post">
         {% csrf_token %}
         {{form|crispy}}
         <button class="btn btn-success">send</button>
    </form>
</section>
{% endblock %}

news/templates/pages/accounts/password_reset_complete.html
{% extends 'master/master.html'%}
{% block content %}
<section id="contentSection">
    <h1>Sucess</h1>

    <a href="{% url 'login' %}" class="btn btn-danger btn-sm">Go to Login</a>
</section>
{% endblock %}

news/templates/pages/accounts/register.html
{% extends 'master/master.html'%}
{% block content %}
{% load crispy_forms_tags %}
<section id="contentSection" xmlns="http://www.w3.org/1999/html">
    <h1>Register</h1>
    <hr>
    {% if messages %}
    {% for message in messages %}
      <div class="alert alert-success">{{ message }}</div>
    {% endfor %}
    {% endif %}
    <form action="{% url 'register'%}" method="POST">
        {% csrf_token %}
        {{userRegister|crispy}}
        <button class="btn btn-success">Register</button>
    </form>
</section>
{% endblock %}

news/templates/pages/contact.html
{% extends 'master/master.html'%}
{% block content %}
{% load crispy_forms_tags %}
<section id="contentSection">
    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-8">
        <div class="left_content">
          <div class="contact_area">
            <h2>Contact Us</h2>
              {% if messages %}
                 {% for message in messages %}
                     <div class="alert alert-success">{{ message }}</div>
                 {% endfor %}
              {% endif %}

               <form action="{% url 'contact' %}"  method="post">
                     {% csrf_token %}
                     {{form|crispy}}
                     <button class="btn btn-success">Send</button>
               </form>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-4">
        <div class="latest_post">
          <h2><span>Latest News</span></h2>
          <div class="latest_post_container">
            <div id="prev-button"><i class="fa fa-chevron-up"></i></div>
            <ul class="latest_postnav">
              {% for lnews in latestnewsData %}
                  <li>
                    <div class="media"> <a href="{% url 'latestnews-details' lnews.slug %}" class="featured_img"> <img alt="" src="{{ lnews.image.url }}"></a>
                       <h2><span><a href="{% url 'latestnews-details' lnews.slug %}" class="catg_title">{{ lnews.title }}</a></span></h2>
                      <div class="media-body">  {{ lnews.description|slice:"255"|safe }} </div>
                    </div>
                  </li>
              {% endfor %}
            </ul>
            <div id="next-button"><i class="fa  fa-chevron-down"></i></div>
          </div>
        </div>
    </div>
    </div>
  </section>
{% endblock %}

news/templates/pages/index.html
{% extends 'master/master.html'%}
{% block content %}
  <section id="sliderSection">
    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-8">
        <div class="slick_slider">
          {% for slider in sliderData %}
          <div class="single_iteam"> <a href="{% url 'slider-details' slider.slug %}">
            <img src="{{ slider.image.url }}" alt=""></a>
            <div class="slider_article">
              <h2><a class="slider_tittle">{{ slider.title }}</a></h2>
              <p>
                {{ slider.description|slice:"255"|safe }}
              </p>
            </div>
          </div>
          {% endfor %}

        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-4">
        <div class="latest_post">
          <h2><span>Latest News</span></h2>
          <div class="latest_post_container">
            <div id="prev-button"><i class="fa fa-chevron-up"></i></div>
            <ul class="latest_postnav">
              {% for lnews in latestnewsData %}
                  <li>
                    <div class="media"> <a href="{% url 'latestnews-details' lnews.slug %}" class="featured_img"> <img alt="" src="{{ lnews.image.url }}"></a>
                       <h2><span><a href="{% url 'latestnews-details' lnews.slug %}" class="catg_title">{{ lnews.title }}</a></span></h2>
                      <div class="media-body">  {{ lnews.description|slice:"255"|safe }} </div>
                    </div>
                  </li>
              {% endfor %}
            </ul>
            <div id="next-button"><i class="fa  fa-chevron-down"></i></div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section id="contentSection">
    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-8">
        <div class="left_content">
          <div class="single_post_content">
            <h2><span>News</span></h2>
            <div class="single_post_content_left">
              <ul class="business_catgnav  wow fadeInDown">
                {% for news in newsDetailsData %}
                    <li>
                      <figure class="bsbig_fig"> <a href="{% url 'news-details' news.slug %}" class="featured_img"> <img alt="" src="{{ news.image.url }}"> <span class="overlay"></span> </a>
                        <figcaption> <a href="{% url 'news-details' news.slug %}">{{ news.title }}</a> </figcaption>
                        <p>{{ news.description|slice:"255"|safe }}</p>
                      </figure>
                    </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

news/templates/pages/latestnews-details.html
{% extends 'master/master.html'%}
{% block content %}
<section id="contentSection">
    <h1>Latest News</h1>
     {% for lnews in latestnewsData %}
    <h3><a href="">{{ lnews.title }}</a></h3>
    <img src="{{ lnews.image.url }}" class="img-responsive" alt="">
    <p>
        {{ lnews.description|safe }}
    </p>
    {% endfor %}
</section>
{% endblock %}

news/templates/pages/news-details.html
{% extends 'master/master.html'%}
{% block content %}
<section id="contentSection">
    <h1> News Details </h1>
    {% for news in newsDetailsData %}
    <h3><a href="">{{ news.title }}</a></h3>
    <span class="label label-danger">
    {{ news.posted_date }}
    </span>
    <span class="label label-success">
        Posted By {{ news.posted_by|title }}
    </span>

    <span class="label label-info">
        Category {{ news.category|title }}
    </span>

    <img src="{{ news.image.url }}" class="img-responsive" alt="">
    <p>
        {{ news.description|safe }}
    </p>
    {% endfor %}

    <div class="fb-comments" data-href="http://127.0.0.1:8000/news-details/{{news.slug_id}}" data-width="" data-numposts="5"></div>
</section>
{% endblock %}

news/templates/pages/slider-details.html
{% extends 'master/master.html'%}
{% block content %}
<section id="contentSection">
    <h1>Slider Details</h1>

    {% for slider in sliderData %}
    <h3><a href="">{{ slider.title }}</a></h3>
    <img src="{{ slider.image.url }}" class="img-responsive" alt="">
    <p>
        {{ slider.description|safe }}
    </p>
    {% endfor %}

</section>
{% endblock %}

news/templates/pages/user.html
{% extends 'master/master.html'%}
{% block content %}
<section id="contentSection">
    <h1>Users-Details</h1>
    <h3><a href="">Welcome {{ user.get_username|title }}</a></h3>
</section>
{% endblock %}